version: '3'
services:
  nginx:
    networks:
      - certificado
      - meuifpoa
    build: ./docker
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt  # Certificados gerados
      - ./certbot/www:/var/www/certbot   # Desafio ACME
    ports:
      - "80:80"
      - "443:443"

  meuifrspoa:
    image: leogoandete/app-ifrsback-jsoup
    networks:
      - meuifpoa
  certbot:
    image: certbot/certbot
    networks:
      - certificado
    command: certonly --webroot --webroot-path=/var/www/certbot --email leonardo.goandete1@gmail.com --agree-tos --no-eff-email -d app.poa.ifrs.edu.br
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

networks:
  certificado:
    driver: bridge
  meuifpoa:
    driver: bridge
