# Etapa 1: Build da aplicação
FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /app

COPY .mvn/ .mvn/
COPY mvnw /app/mvnw
COPY pom.xml /app/pom.xml

# Baixa as dependências para a compilação
RUN ./mvnw dependency:go-offline

COPY ./src/main/ ./src/main/

# Empacota a aplicação como um Uber Jar
RUN ./mvnw package -Dquarkus.package.type=uber-jar

# Etapa 2: Configuração do ambiente de execução com Playwright no Alpine
FROM eclipse-temurin:21-jre-alpine AS app

# Instalar Node.js e NPM no Alpine
RUN apk add --no-cache nodejs npm

# Instalar dependências do Playwright no Alpine
RUN apk add --no-cache \
    nss \
    freetype \
    harfbuzz \
    ttf-freefont \
    ca-certificates \
    libxcomposite \
    libxrandr \
    libxdamage \
    libxtst \
    libxshmfence \
    mesa-gl \
    dbus-glib \
    libgcc \
    libstdc++ \
    chromium \
    firefox \
    firefox-esr \
    xvfb \
    ffmpeg \
    git \
    bash

# Copiar navegadores do Playwright da imagem oficial (opcional)
COPY --from=mcr.microsoft.com/playwright:v1.47.2-focal /ms-playwright /ms-playwright

# Definir variável de ambiente para Playwright
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

# Adicionar um grupo e um usuário não-root
#RUN addgroup -S appgroup && \
#    adduser -S appuser -G appgroup

# Mudar para o usuário não-root
#USER appuser

# Copiar o Jar gerado na etapa de build
COPY --from=build /app/target/*.jar /app/app.jar

# Expor a porta 8080
EXPOSE 8080

# Comando de entrada para iniciar a aplicação
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
