quarkus.redis.hosts=redis://localhost:6379
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=hibernate
quarkus.datasource.password=hibernate
quarkus.datasource.jdbc.url=jdbc:postgresql://172.17.0.5:5432/quarkus
quarkus.hibernate-orm.database.generation= drop-and-create
mp.jwt.verify.issuer=http://localhost:8080
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.smallrye-jwt.enabled=true
quarkus.smallrye-jwt.token-signing-key-location=privateKey.pem
quarkus.smallrye-jwt.realm=localhost
quarkus.swagger-ui.always-include=true
quarkus.smallrye-jwt.public-key.location=publicKey.pem
#Habilitar o docker para a aplicação
#quarkus.datasource.devservices.enabled=true