quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}
quarkus.scheduler.cron-type=unix
#executa a cada Hora
agendamento=0 * * * *
quarkus.http.cors=false
quarkus.http.cors.origins=/.*/
mp.jwt.verify.issuer=https://securetoken.google.com/ifrspoa-d9f18
mp.jwt.verify.publickey.location=key.pem
quarkus.smallrye-jwt.public-key.location=key.pem
quarkus.smallrye-jwt.enabled=true