quarkus.http.host=0.0.0.0
quarkus.http.port=${PORT:8080}
quarkus.http.cors=false
quarkus.http.cors.origins=/.*/
quarkus.swagger-ui.enable=true
quarkus.swagger-ui.always-include=true
#mp.jwt.verify.issuer=https://securetoken.google.com/ifrspoa-d9f18
#mp.jwt.verify.publickey.location=google-key.pem
#quarkus.smallrye-jwt.public-key.location=https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
quarkus.smallrye-jwt.enabled=true
smallrye.jwt.verify.key.location=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
mp.jwt.verify.issuer=https://securetoken.google.com/ifrspoa-d9f18

%dev.quarkus.smallrye-openapi.path=/q/openapi
%prod.quarkus.smallrye-openapi.path=/meuifpoa/q/openapi
%dev.quarkus.swagger-ui.path=/q/swagger-ui
%prod.quarkus.swagger-ui.path=/meuifpoa/q/swagger-ui
%prod.quarkus.swagger-ui.always-include=true



