name: SonarCloud
on:
  push:
    branches:
      - main

jobs:
  gerando-imagem-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Build do projeto
        run: docker build -t leogoandete/app-ifrsback .

      - name: Autenticando no docker registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Enviando a imagem para o Dockerhub
        run: docker push leogoandete/app-ifrsback
